import type { College } from "./types";

/**
 * 5 fictional colleges spanning the Indian higher-ed landscape.
 * Names + facts are invented to avoid defamation; tonal flavor preserved.
 */
export const colleges: College[] = [
  {
    slug: "institute-technical-excellence-bombay",
    name: "Institute of Technical Excellence, Bombay",
    shortName: "ITE Bombay",
    city: "Mumbai",
    state: "Maharashtra",
    founded: 1958,
    category: "engineering",
    tier: "tier-1",
    caseFileNumber: "UF-0001",
    /* All colleges share the single editorial accent. Per-college identity
       lives in the generative fingerprint *pattern* (driven by fingerprintSeed),
       not its colour — keeps the palette restrained. */
    primaryAccent: "#FF4332",
    fingerprintSeed: "ite-bom-1958-tier1-eng",
    truthScore: 78,
    reviewCount: 412,
    verifiedCount: 318,
    tagline: "The crown jewel of Indian engineering. Allegedly.",
    brochureBlurb:
      "Globally ranked. Industry-leading placements. State-of-the-art research labs. Vibrant campus life across 550 verdant acres. Mentorship from Padma Shri faculty. The pinnacle of technical education in South Asia.",
    brochureClaims: [
      {
        id: "claim-1",
        claim: "100% placement record for the graduating class.",
        truth: "84% if you include unpaid internships. 71% for full-time roles above ₹6 LPA. Some branches: 48%.",
        category: "placements",
        delta: 52,
      },
      {
        id: "claim-2",
        claim: "Average package ₹22 LPA, highest ₹2.1 Cr international.",
        truth: "Median ₹14 LPA. The ₹2.1 Cr was a single PPO from a HFT firm to one student. Median international: ₹38 LPA.",
        category: "placements",
        delta: 36,
      },
      {
        id: "claim-3",
        claim: "Mentorship from world-renowned, globally-cited faculty.",
        truth: "60% of UG courses taught by PhD students. Star faculty teach 1 elective for visibility.",
        category: "faculty",
        delta: 41,
      },
      {
        id: "claim-4",
        claim: "State-of-the-art labs and research infrastructure.",
        truth: "Mech lab equipment dates to 1989. Booking a 3D printer requires 5 days. CS labs are excellent.",
        category: "infrastructure",
        delta: 28,
      },
      {
        id: "claim-5",
        claim: "Vibrant, inclusive campus life.",
        truth: "Excellent if you're in a tech-club bubble. Mental health waitlist: 6 weeks. Hostel mess strike average: 2x/sem.",
        category: "campus-life",
        delta: 33,
      },
    ],
    placementData: [
      { year: 2021, claimedPercentage: 100, verifiedPercentage: 72, claimedAvgLpa: 19.5, verifiedAvgLpa: 12.8 },
      { year: 2022, claimedPercentage: 100, verifiedPercentage: 76, claimedAvgLpa: 21.2, verifiedAvgLpa: 13.6 },
      { year: 2023, claimedPercentage: 100, verifiedPercentage: 71, claimedAvgLpa: 22.4, verifiedAvgLpa: 14.1 },
      { year: 2024, claimedPercentage: 100, verifiedPercentage: 69, claimedAvgLpa: 22.0, verifiedAvgLpa: 14.0 },
    ],
    longRead: {
      deck: "Inside India's most-photographed campus, where the gulf between brochure and reality stretches as wide as the Powai lake.",
      paragraphs: [
        "Walk past the main building at sunset, and you understand why the photographs sell. Sodium light bleeds across red brick. Students in branded fest tees jog by. The story almost tells itself.",
        "But the story it sells is not the story most students live. In 47 interviews — first-years to alumni five years out — a different campus emerges. One of brilliant pockets and forgotten corridors, of star faculty who appear in publicity stills and graduate students who actually grade your work.",
        "The placement numbers are the most contested artifact. The institute publishes 100% every year. Verified data from the placement office, obtained through three former coordinators, shows the figure dropping to 71% once you exclude unpaid internships, deferred offers, and PPOs from family-run firms.",
        "None of which means the institute is not extraordinary. It is. But brochures, like ours used to be, choose which extraordinariness to print.",
      ],
      pullQuote: "The story this campus sells is not the story most students live.",
      byline: "Filed by UNFILTERED · 47 verified sources",
    },
    feeStructure: {
      claimed: 230000,
      actual: 412000,
      note: "Hostel mess + lab fees + branch electives + insurance + graduation fee.",
    },
  },
  {
    slug: "sai-deemed-university",
    name: "Sai Deemed-To-Be University",
    shortName: "Sai DU",
    city: "Bengaluru",
    state: "Karnataka",
    founded: 1996,
    category: "private-deemed",
    tier: "tier-2",
    caseFileNumber: "UF-0017",
    primaryAccent: "#FF4332",
    fingerprintSeed: "sai-du-1996-tier2-private",
    truthScore: 41,
    reviewCount: 287,
    verifiedCount: 198,
    tagline: "The brochure smells of jasmine. The classrooms smell of mould.",
    brochureBlurb:
      "Sai Deemed-To-Be University: where ancient wisdom meets futuristic learning. International tie-ups. AICTE-approved. Naac A+. Placements with top MNCs. Campus inspired by traditional Indian architecture.",
    brochureClaims: [
      {
        id: "claim-1",
        claim: "International tie-ups with 40+ universities across 15 countries.",
        truth: "12 MoUs total, 4 active. 'Tie-up' = one professor co-authored a paper in 2018.",
        category: "infrastructure",
        delta: 71,
      },
      {
        id: "claim-2",
        claim: "92% placement record.",
        truth: "31% verified for non-IT branches. Civil and Mechanical: ~14%. IT is the only thing keeping the number alive.",
        category: "placements",
        delta: 67,
      },
      {
        id: "claim-3",
        claim: "AICTE-approved, NAAC A+ rated.",
        truth: "AICTE approval is real. NAAC A+ expired in 2022; re-accreditation pending. The website still uses the old badge.",
        category: "infrastructure",
        delta: 88,
      },
      {
        id: "claim-4",
        claim: "Hostel inspired by traditional Indian architecture.",
        truth: "Three hostels. One has hot water. The 'traditional architecture' is a stone arch at the gate. Inside: cement.",
        category: "campus-life",
        delta: 62,
      },
      {
        id: "claim-5",
        claim: "Affordable, all-inclusive fee structure.",
        truth: "Sticker fee ₹2.8L/year. Actual outflow with hostel, mess, lab, exam, library, late-fee penalties: ₹4.6L.",
        category: "fees",
        delta: 64,
      },
    ],
    placementData: [
      { year: 2021, claimedPercentage: 92, verifiedPercentage: 38, claimedAvgLpa: 8.2, verifiedAvgLpa: 4.1 },
      { year: 2022, claimedPercentage: 94, verifiedPercentage: 34, claimedAvgLpa: 8.9, verifiedAvgLpa: 4.3 },
      { year: 2023, claimedPercentage: 92, verifiedPercentage: 31, claimedAvgLpa: 9.1, verifiedAvgLpa: 4.0 },
      { year: 2024, claimedPercentage: 91, verifiedPercentage: 29, claimedAvgLpa: 9.4, verifiedAvgLpa: 4.2 },
    ],
    longRead: {
      deck: "A private deemed university spent ₹14 crores on its brochure last year. Students paid for it. Twice.",
      paragraphs: [
        "The Sai Deemed campus does not look like an academic institution. It looks like a real-estate brochure printed in three dimensions. Marble. Fountains. A statue of the founder, gilded, eight feet high.",
        "The marble is real. The marble is also where the budget went. The civil engineering laboratory, four floors above the founder's statue, has not had a working oscilloscope since 2021.",
        "The NAAC A+ badge that appears on every page of the prospectus — every form, every receipt, every banner at every job-fair — expired in October 2022. Students are not told this. Recruiters increasingly are.",
      ],
      pullQuote: "The marble is real. The lab is not.",
      byline: "Filed by UNFILTERED · 31 verified sources",
    },
    feeStructure: {
      claimed: 280000,
      actual: 462000,
      note: "Hostel + mess + lab + exam + library + 'development' fees.",
    },
  },
  {
    slug: "nila-academy-of-arts",
    name: "Nila Academy of Arts and Design",
    shortName: "Nila Arts",
    city: "Pondicherry",
    state: "Puducherry",
    founded: 2004,
    category: "arts",
    tier: "tier-2",
    caseFileNumber: "UF-0042",
    primaryAccent: "#FF4332",
    fingerprintSeed: "nila-arts-2004-tier2",
    truthScore: 67,
    reviewCount: 134,
    verifiedCount: 102,
    tagline: "Romance in the brochure. Reality in the rent.",
    brochureBlurb:
      "Nila Academy: where the artist becomes the work. A 17-acre coastal campus. Visiting artists from Berlin, Tokyo, New York. Studio space for every student. Industry-leading placement in design houses, ad agencies, and gallery representation.",
    brochureClaims: [
      {
        id: "claim-1",
        claim: "Visiting artists from Berlin, Tokyo, and New York throughout the academic year.",
        truth: "2 visits in 2023, 3 in 2024. Most 'visiting artists' are alumni-friends doing 90-min talks via Zoom.",
        category: "faculty",
        delta: 58,
      },
      {
        id: "claim-2",
        claim: "Dedicated studio space for every student.",
        truth: "True for fine-arts (good). False for design — 4 students/desk, shifts after 6pm.",
        category: "infrastructure",
        delta: 44,
      },
      {
        id: "claim-3",
        claim: "Industry-leading placement in top design houses.",
        truth: "Placement support is genuinely strong for graphic design. Fine arts: you're on your own with a portfolio.",
        category: "placements",
        delta: 31,
      },
      {
        id: "claim-4",
        claim: "17-acre coastal campus.",
        truth: "11 acres. The other 6 are a partner organisation's land used 2x/year for the fest.",
        category: "campus-life",
        delta: 35,
      },
      {
        id: "claim-5",
        claim: "Affordable hostel adjacent to the campus.",
        truth: "Hostel rents are 2.4× the going Pondicherry rate. Most students move out by year 2.",
        category: "fees",
        delta: 48,
      },
    ],
    placementData: [
      { year: 2021, claimedPercentage: 88, verifiedPercentage: 62, claimedAvgLpa: 6.0, verifiedAvgLpa: 3.8 },
      { year: 2022, claimedPercentage: 90, verifiedPercentage: 64, claimedAvgLpa: 6.4, verifiedAvgLpa: 4.0 },
      { year: 2023, claimedPercentage: 91, verifiedPercentage: 67, claimedAvgLpa: 6.8, verifiedAvgLpa: 4.4 },
      { year: 2024, claimedPercentage: 92, verifiedPercentage: 69, claimedAvgLpa: 7.1, verifiedAvgLpa: 4.5 },
    ],
    longRead: {
      deck: "An art school built on the romance of the coast. The romance bills monthly.",
      paragraphs: [
        "Nila Academy is the only college in this investigation that genuinely loves its students. The faculty know their names. The studios stay open at 2am. Visitors leave with a portfolio.",
        "It is also one of the most expensive places in the country to study fine art. Not in tuition — in the slow bleed of rents inflated by the institution's gravity, in materials priced above market by the lone supplier the academy 'recommends,' in the cost of the train to a city that has the gallery you need to visit.",
        "The brochure does not lie about the campus. It lies, by omission, about who can afford to stay on it.",
      ],
      pullQuote: "The college does not lie about the campus. It lies, by omission, about who can stay on it.",
      byline: "Filed by UNFILTERED · 22 verified sources",
    },
    feeStructure: {
      claimed: 195000,
      actual: 312000,
      note: "Studio materials + hostel premium + city travel + portfolio printing.",
    },
  },
  {
    slug: "asianova-business-school",
    name: "Asianova Business School",
    shortName: "ABS",
    city: "Hyderabad",
    state: "Telangana",
    founded: 2009,
    category: "business",
    tier: "tier-2",
    caseFileNumber: "UF-0073",
    primaryAccent: "#FF4332",
    fingerprintSeed: "abs-2009-tier2-mba",
    truthScore: 52,
    reviewCount: 211,
    verifiedCount: 156,
    tagline: "Ranked #4 by a magazine they sponsor.",
    brochureBlurb:
      "Asianova Business School. Ranked #4 in South India. Median CTC ₹17.4 LPA. Faculty from Wharton, INSEAD, IIMs. Corporate engagement with 380+ recruiters. The MBA destination of choice.",
    brochureClaims: [
      {
        id: "claim-1",
        claim: "Ranked #4 in South India by Business Today.",
        truth: "Ranked #4 in a paid-survey vertical of a sister publication. Independent rankings: #19, #22.",
        category: "infrastructure",
        delta: 72,
      },
      {
        id: "claim-2",
        claim: "Median CTC ₹17.4 LPA across the class of 2024.",
        truth: "Median ₹11.2 LPA. The ₹17.4 number includes ESOPs and 'expected bonuses' over 3 years.",
        category: "placements",
        delta: 53,
      },
      {
        id: "claim-3",
        claim: "Faculty from Wharton, INSEAD, IIM-A.",
        truth: "Three adjuncts with the credential. Each teaches one elective. Core curriculum: ABS internal faculty.",
        category: "faculty",
        delta: 47,
      },
      {
        id: "claim-4",
        claim: "380+ recruiters engaged annually.",
        truth: "112 active recruiters in 2024. 'Engaged' includes campus-tour visits and one-off webinars.",
        category: "placements",
        delta: 58,
      },
      {
        id: "claim-5",
        claim: "Modern, tech-enabled classrooms.",
        truth: "Genuinely good. The classrooms are the best part of the school.",
        category: "infrastructure",
        delta: 5,
      },
    ],
    placementData: [
      { year: 2021, claimedPercentage: 98, verifiedPercentage: 81, claimedAvgLpa: 15.2, verifiedAvgLpa: 9.8 },
      { year: 2022, claimedPercentage: 99, verifiedPercentage: 79, claimedAvgLpa: 16.4, verifiedAvgLpa: 10.4 },
      { year: 2023, claimedPercentage: 99, verifiedPercentage: 76, claimedAvgLpa: 17.0, verifiedAvgLpa: 10.9 },
      { year: 2024, claimedPercentage: 99, verifiedPercentage: 74, claimedAvgLpa: 17.4, verifiedAvgLpa: 11.2 },
    ],
    longRead: {
      deck: "How an MBA programme manufactured a #4 ranking, then printed it on the front of every brochure.",
      paragraphs: [
        "Asianova Business School's brochure for the 2024 intake opens, on its very first page, with one number: 4. As in, ranked fourth. As in, you should pay ₹24 lakhs to attend the fourth-best business school in South India.",
        "The ranking is technically real. It was published by a magazine. The magazine is owned by a media group that, public filings confirm, also sells 'brand-engagement packages' to business schools. ABS's package, in 2024, was ₹38 lakhs.",
        "The faculty problem is more interesting. ABS does have professors from Wharton, INSEAD, and the IIMs. Three of them. They teach one elective each. The other 80% of contact hours are with internal faculty whose credentials are competent but rarely the calibre advertised.",
      ],
      pullQuote: "₹24 lakhs to attend the fourth-best business school in South India. Ranked by a magazine they paid.",
      byline: "Filed by UNFILTERED · 38 verified sources",
    },
    feeStructure: {
      claimed: 2400000,
      actual: 2830000,
      note: "Tuition + hostel + international module + alumni-network fee + graduation gala.",
    },
  },
  {
    slug: "kaveri-regional-university",
    name: "Kaveri Regional University",
    shortName: "KRU",
    city: "Salem",
    state: "Tamil Nadu",
    founded: 1979,
    category: "regional",
    tier: "tier-3",
    caseFileNumber: "UF-0118",
    primaryAccent: "#FF4332",
    fingerprintSeed: "kru-1979-tier3-regional",
    truthScore: 84,
    reviewCount: 96,
    verifiedCount: 79,
    tagline: "The brochure undersells it. The students don't.",
    brochureBlurb:
      "Kaveri Regional University. Affordable. Local. 45 years of community service. Bachelors, masters, doctoral programmes across the sciences and humanities.",
    brochureClaims: [
      {
        id: "claim-1",
        claim: "Affordable education for the local community.",
        truth: "Genuinely is. Tuition ₹14k/year. Hidden costs minimal. Most reviewed item: 'no scams here'.",
        category: "fees",
        delta: 4,
      },
      {
        id: "claim-2",
        claim: "Comprehensive academic programmes.",
        truth: "Curriculum is dated, especially in CS and electronics. Faculty try harder than the syllabus.",
        category: "faculty",
        delta: 22,
      },
      {
        id: "claim-3",
        claim: "Strong community service tradition.",
        truth: "True. NSS and outreach programmes are genuinely embedded in campus culture.",
        category: "campus-life",
        delta: 8,
      },
      {
        id: "claim-4",
        claim: "Modern library and lab facilities.",
        truth: "Library is unexpectedly excellent. Labs are functional, equipment 10+ years old.",
        category: "infrastructure",
        delta: 26,
      },
      {
        id: "claim-5",
        claim: "Placement support available.",
        truth: "Genuinely available, genuinely under-resourced. 41% verified placements. PSU exam prep is the real story.",
        category: "placements",
        delta: 18,
      },
    ],
    placementData: [
      { year: 2021, claimedPercentage: 62, verifiedPercentage: 38, claimedAvgLpa: 3.4, verifiedAvgLpa: 2.6 },
      { year: 2022, claimedPercentage: 64, verifiedPercentage: 41, claimedAvgLpa: 3.6, verifiedAvgLpa: 2.8 },
      { year: 2023, claimedPercentage: 65, verifiedPercentage: 42, claimedAvgLpa: 3.7, verifiedAvgLpa: 2.9 },
      { year: 2024, claimedPercentage: 66, verifiedPercentage: 41, claimedAvgLpa: 3.8, verifiedAvgLpa: 3.0 },
    ],
    longRead: {
      deck: "A regional university built no marketing department, and accidentally became the most honest institution in this investigation.",
      paragraphs: [
        "Kaveri Regional University's brochure is six pages long. It is printed on uncoated stock. The most decorated faculty member appears on page four, in a thumbnail. The institution is, in every measurable way, the least photogenic college we investigated.",
        "It is also the only one whose graduates uniformly said the brochure was honest. 'They didn't promise me anything,' said a 2023 alumna, now a junior assistant in a district collectorate. 'So I wasn't lied to.'",
        "Kaveri is not the best university in this story. It is the only one whose marketing department, in budget terms, is smaller than its placement-counselling cell.",
      ],
      pullQuote: "They didn't promise me anything. So I wasn't lied to.",
      byline: "Filed by UNFILTERED · 19 verified sources",
    },
    feeStructure: {
      claimed: 14000,
      actual: 21000,
      note: "Tuition + library card + exam fee + lab consumables.",
    },
  },
];
