import type { Review } from "./types";

/**
 * 60+ reviews across 5 colleges (~12 each).
 * Vibes vary deliberately — rage, warm, deadpan, warning, redeemed —
 * so the Evidence Wall has tonal range, not just a single complaint loop.
 */

const verified = (d: string): Review["verification"] => ({
  method: "id-card",
  verifiedAt: d,
});

export const reviews: Review[] = [
  // ───────────────── ITE BOMBAY ─────────────────
  { id: "r-ite-01", collegeSlug: "institute-technical-excellence-bombay", authorPseudonym: "Echo-841", authorYear: 4, authorBranch: "Computer Science",
    rating: 4, truthScore: 72, title: "CS is genuinely world-class. Everything else, depends.",
    body: "If you got CS at ITE Bombay, you won. The faculty, the labs, the peer group — all real. But the brochure makes it sound like every branch is CS. Civil and Metallurgy live on a different campus, with different equipment, and a different reality.",
    tags: ["academics", "placements", "branch-bias"], vibe: "deadpan", hasVideo: false,
    verification: verified("2024-08-12T10:00:00Z"), publishedAt: "2024-10-04T13:00:00Z", upvotes: 412, receipts: 3 },
  { id: "r-ite-02", collegeSlug: "institute-technical-excellence-bombay", authorPseudonym: "Lighthouse-22", authorYear: 5, authorBranch: "Mechanical (Alumni)",
    rating: 2, truthScore: 38, title: "I was the placement statistic.",
    body: "Brochure said 100%. I was placed on the 17th of the month, in a job I left in 4 months. The institute's number went up. I went home. The placement cell knew this. The next year's brochure did not.",
    tags: ["placements", "lies"], vibe: "rage", hasVideo: true,
    verification: { method: "alumni-roster", verifiedAt: "2024-09-01T10:00:00Z" }, publishedAt: "2024-11-15T09:00:00Z", upvotes: 1804, receipts: 7 },
  { id: "r-ite-03", collegeSlug: "institute-technical-excellence-bombay", authorPseudonym: "Monsoon-09", authorYear: 3, authorBranch: "Electrical",
    rating: 5, truthScore: 88, title: "The campus genuinely is beautiful.",
    body: "The monsoons here are unforgettable. The library on a Sunday morning. The lake. The brochure cannot oversell the campus because the campus is the one thing the brochure was honest about.",
    tags: ["campus-life", "warmth"], vibe: "warm", hasVideo: false,
    verification: verified("2024-07-20T10:00:00Z"), publishedAt: "2024-08-18T16:00:00Z", upvotes: 921, receipts: 0 },
  { id: "r-ite-04", collegeSlug: "institute-technical-excellence-bombay", authorPseudonym: "Decibel-44", authorYear: 4, authorBranch: "Aerospace",
    rating: 3, truthScore: 60, title: "Faculty mentorship is a Schelling point.",
    body: "If you're proactive, the faculty are extraordinary. If you're shy or struggling, you will be invisible for four years and graduate without anyone knowing your name. The brochure shows the lucky 20%.",
    tags: ["faculty"], vibe: "deadpan", hasVideo: false,
    verification: verified("2024-06-05T10:00:00Z"), publishedAt: "2024-09-01T11:00:00Z", upvotes: 612, receipts: 1 },
  { id: "r-ite-05", collegeSlug: "institute-technical-excellence-bombay", authorPseudonym: "Vellum-12", authorYear: 2, authorBranch: "Civil",
    rating: 2, truthScore: 41, title: "The Civil lab equipment dates to 1989.",
    body: "Litmus paper, manual surveying chains, a single working theodolite. The brochure shows a CS lab with curved monitors. Civil engineering is run on goodwill and a department head who fights for every rupee.",
    tags: ["infrastructure", "branch-bias"], vibe: "warning", hasVideo: false,
    verification: verified("2024-05-10T10:00:00Z"), publishedAt: "2024-08-04T10:00:00Z", upvotes: 488, receipts: 4 },
  { id: "r-ite-06", collegeSlug: "institute-technical-excellence-bombay", authorPseudonym: "Quartz-77", authorYear: 5, authorBranch: "CS (Alumni)",
    rating: 5, truthScore: 79, title: "If I had to do it again, I would.",
    body: "Everything UNFILTERED says about this place is true. Including the rough edges. It is still, in 2024, the single best decision I made before age 22. The brochure didn't get me here — JEE rank did. So we can be honest now.",
    tags: ["alumni", "warmth"], vibe: "redeemed", hasVideo: false,
    verification: { method: "alumni-roster", verifiedAt: "2024-03-12T10:00:00Z" }, publishedAt: "2024-10-22T18:00:00Z", upvotes: 2104, receipts: 2 },
  { id: "r-ite-07", collegeSlug: "institute-technical-excellence-bombay", authorPseudonym: "Iodine-13", authorYear: 1, authorBranch: "Chemical",
    rating: 3, truthScore: 65, title: "First-year is harder than they tell you.",
    body: "Workload, mental health waitlist, hostel issues — first year hits hard. The brochure promised 'vibrant community.' The community is real but you have to find it. It does not find you.",
    tags: ["campus-life", "mental-health"], vibe: "warning", hasVideo: false,
    verification: verified("2024-09-25T10:00:00Z"), publishedAt: "2024-11-02T13:00:00Z", upvotes: 256, receipts: 1 },
  { id: "r-ite-08", collegeSlug: "institute-technical-excellence-bombay", authorPseudonym: "Halftone-58", authorYear: 4, authorBranch: "CS",
    rating: 4, truthScore: 70, title: "Faculty are world-class. They teach 1 course each.",
    body: "I had the Padma Shri prof on the brochure cover. For one course. For 14 weeks. The other 7 semesters were taught by very competent grad students. The brochure shows the cover photo. Just know that going in.",
    tags: ["faculty", "transparency"], vibe: "deadpan", hasVideo: false,
    verification: verified("2024-04-18T10:00:00Z"), publishedAt: "2024-07-30T12:00:00Z", upvotes: 511, receipts: 0 },
  { id: "r-ite-09", collegeSlug: "institute-technical-excellence-bombay", authorPseudonym: "Cinder-30", authorYear: 3, authorBranch: "Mechanical",
    rating: 2, truthScore: 44, title: "Mech placements are not what the brochure shows.",
    body: "The brochure highlights a ₹2.1 Cr international PPO. That was one CS student. In Mech, average package this year was ₹6.4 LPA. Three classmates took core-mech jobs at ₹3.8.",
    tags: ["placements", "branch-bias"], vibe: "rage", hasVideo: true,
    verification: verified("2024-06-30T10:00:00Z"), publishedAt: "2024-09-12T14:00:00Z", upvotes: 1188, receipts: 5 },
  { id: "r-ite-10", collegeSlug: "institute-technical-excellence-bombay", authorPseudonym: "Marina-04", authorYear: 5, authorBranch: "CS (Alumni)",
    rating: 5, truthScore: 82, title: "What the brochure left out: the people.",
    body: "The institution did not make me. The 800 humans I lived with for four years made me. The brochure could have led with that. It led with rankings.",
    tags: ["warmth", "alumni"], vibe: "warm", hasVideo: false,
    verification: { method: "alumni-roster", verifiedAt: "2024-02-04T10:00:00Z" }, publishedAt: "2024-08-25T11:00:00Z", upvotes: 1402, receipts: 0 },
  { id: "r-ite-11", collegeSlug: "institute-technical-excellence-bombay", authorPseudonym: "Ferrule-91", authorYear: 2, authorBranch: "Metallurgy",
    rating: 3, truthScore: 58, title: "The department nobody photographs.",
    body: "Met is the smallest, oldest, most under-funded department on campus. Faculty are great. Equipment is older than my parents. The brochure does not contain a single photo from our department.",
    tags: ["infrastructure"], vibe: "deadpan", hasVideo: false,
    verification: verified("2024-08-02T10:00:00Z"), publishedAt: "2024-10-15T15:00:00Z", upvotes: 188, receipts: 2 },
  { id: "r-ite-12", collegeSlug: "institute-technical-excellence-bombay", authorPseudonym: "Pyrite-66", authorYear: 4, authorBranch: "CS",
    rating: 4, truthScore: 75, title: "Brand opens doors. Don't confuse it with skill.",
    body: "ITE Bombay opens doors. So does your work. Some of my peers got jobs on the strength of the brand alone — then struggled. The brochure sells the brand. Build the skill anyway.",
    tags: ["placements", "advice"], vibe: "warm", hasVideo: false,
    verification: verified("2024-05-18T10:00:00Z"), publishedAt: "2024-09-08T17:00:00Z", upvotes: 712, receipts: 0 },

  // ───────────────── SAI DEEMED UNIVERSITY ─────────────────
  { id: "r-sai-01", collegeSlug: "sai-deemed-university", authorPseudonym: "Granite-55", authorYear: 3, authorBranch: "Civil",
    rating: 1, truthScore: 24, title: "I am suing the university.",
    body: "I will keep this short. The lab equipment doesn't work. The brochure promised an Italy semester that was cancelled three days before flights. The 'refund' was a credit-note for future semesters. I am suing.",
    tags: ["lies", "fees", "infrastructure"], vibe: "rage", hasVideo: true,
    verification: verified("2024-11-04T10:00:00Z"), publishedAt: "2024-11-22T09:00:00Z", upvotes: 3204, receipts: 9 },
  { id: "r-sai-02", collegeSlug: "sai-deemed-university", authorPseudonym: "Helio-19", authorYear: 4, authorBranch: "Information Technology",
    rating: 3, truthScore: 55, title: "IT is the only thing keeping this place alive.",
    body: "If you got IT and you're hard-working, you'll do fine. The placement number you see is essentially the IT placement number with a Civil/Mech rounding error. Don't come for any other branch.",
    tags: ["placements", "branch-bias"], vibe: "deadpan", hasVideo: false,
    verification: verified("2024-04-22T10:00:00Z"), publishedAt: "2024-08-19T12:00:00Z", upvotes: 814, receipts: 2 },
  { id: "r-sai-03", collegeSlug: "sai-deemed-university", authorPseudonym: "Pebble-72", authorYear: 2, authorBranch: "Biotechnology",
    rating: 2, truthScore: 33, title: "The biotech lab smells of mould.",
    body: "Literally. The PCR machine has not worked since I joined. We submit assignments based on textbook problems, not lab results. The brochure shows a centrifuge from a stock photo.",
    tags: ["infrastructure", "lies"], vibe: "warning", hasVideo: false,
    verification: verified("2024-07-30T10:00:00Z"), publishedAt: "2024-09-25T11:00:00Z", upvotes: 567, receipts: 3 },
  { id: "r-sai-04", collegeSlug: "sai-deemed-university", authorPseudonym: "Aniline-44", authorYear: 5, authorBranch: "Chemical (Alumni)",
    rating: 2, truthScore: 38, title: "Brochure costs ₹0. Hidden fees: ₹1.6L/year.",
    body: "Tuition: ₹2.8L. Hostel mess: ₹84k. Lab consumables: ₹22k. 'Development fee': ₹40k. Exam: ₹14k. Late penalty if you don't pay by the 5th of every month: ₹500/day. Real outflow per year: ₹4.6L.",
    tags: ["fees", "lies"], vibe: "rage", hasVideo: false,
    verification: { method: "alumni-roster", verifiedAt: "2024-01-15T10:00:00Z" }, publishedAt: "2024-09-04T15:00:00Z", upvotes: 1633, receipts: 6 },
  { id: "r-sai-05", collegeSlug: "sai-deemed-university", authorPseudonym: "Marigold-08", authorYear: 4, authorBranch: "IT",
    rating: 3, truthScore: 51, title: "The student community is the only good thing.",
    body: "Faculty are mostly indifferent. Infrastructure is bad. Brochure lies, often. But the students, the friends I made, are why I survived. The campus didn't build us. We built each other.",
    tags: ["campus-life", "warmth"], vibe: "warm", hasVideo: false,
    verification: verified("2024-08-09T10:00:00Z"), publishedAt: "2024-10-18T14:00:00Z", upvotes: 740, receipts: 0 },
  { id: "r-sai-06", collegeSlug: "sai-deemed-university", authorPseudonym: "Tungsten-13", authorYear: 3, authorBranch: "Mechanical",
    rating: 1, truthScore: 22, title: "We were promised an Italy semester.",
    body: "Brochure: 'International Semester at Politecnico di Milano.' Reality: a 2-week tour in 2019 only. Discontinued post-COVID. Brochure 2024 still has the photograph. I asked. I was told to 'check the disclaimer.'",
    tags: ["lies", "international"], vibe: "rage", hasVideo: true,
    verification: verified("2024-09-19T10:00:00Z"), publishedAt: "2024-10-30T16:00:00Z", upvotes: 1980, receipts: 5 },
  { id: "r-sai-07", collegeSlug: "sai-deemed-university", authorPseudonym: "Cobalt-31", authorYear: 2, authorBranch: "Computer Science",
    rating: 3, truthScore: 49, title: "The marble is real. The marble is everything.",
    body: "The campus is genuinely beautiful. Founders' statue, fountains, granite floors. The Civil lab, four floors above, is a corrugated-tin extension. Priorities are legible.",
    tags: ["infrastructure", "lies"], vibe: "deadpan", hasVideo: false,
    verification: verified("2024-06-12T10:00:00Z"), publishedAt: "2024-08-30T11:00:00Z", upvotes: 612, receipts: 2 },
  { id: "r-sai-08", collegeSlug: "sai-deemed-university", authorPseudonym: "Lupine-25", authorYear: 4, authorBranch: "IT",
    rating: 4, truthScore: 64, title: "Came here because of brand. Stayed because of friends.",
    body: "I will not pretend this college is good. But four years here taught me how to be cynical, kind, and self-taught — three skills no T1 college teaches. I am grateful for the wrong reasons.",
    tags: ["warmth", "alumni"], vibe: "redeemed", hasVideo: false,
    verification: verified("2024-04-04T10:00:00Z"), publishedAt: "2024-09-17T19:00:00Z", upvotes: 901, receipts: 0 },
  { id: "r-sai-09", collegeSlug: "sai-deemed-university", authorPseudonym: "Mineral-77", authorYear: 1, authorBranch: "CS",
    rating: 2, truthScore: 39, title: "First-year scam: orientation 'kit'.",
    body: "₹18,000 'orientation kit' on day 1, mandatory. Contents: t-shirt, lanyard, notebook, water bottle, drawstring bag. None of which I use. Brochure does not mention this fee.",
    tags: ["fees", "scam"], vibe: "warning", hasVideo: false,
    verification: verified("2024-10-12T10:00:00Z"), publishedAt: "2024-11-04T10:00:00Z", upvotes: 411, receipts: 2 },
  { id: "r-sai-10", collegeSlug: "sai-deemed-university", authorPseudonym: "Heron-46", authorYear: 5, authorBranch: "IT (Alumni)",
    rating: 3, truthScore: 52, title: "If you can teach yourself, you can survive.",
    body: "My CTC after Sai: ₹6 LPA. After two years self-studying systems design on YouTube: ₹19 LPA. The college did not make my career. YouTube did. The brochure took credit for both.",
    tags: ["placements", "alumni"], vibe: "deadpan", hasVideo: false,
    verification: { method: "alumni-roster", verifiedAt: "2024-02-25T10:00:00Z" }, publishedAt: "2024-08-08T13:00:00Z", upvotes: 1224, receipts: 0 },
  { id: "r-sai-11", collegeSlug: "sai-deemed-university", authorPseudonym: "Slate-88", authorYear: 2, authorBranch: "Civil",
    rating: 1, truthScore: 19, title: "NAAC A+ on every page. NAAC expired in 2022.",
    body: "I noticed the badge on a 2024 leaflet. Looked it up. The NAAC A+ from 2017 expired in 2022. Re-accreditation pending since. The college still prints the badge. I emailed the registrar. No reply.",
    tags: ["lies", "accreditation"], vibe: "rage", hasVideo: false,
    verification: verified("2024-09-08T10:00:00Z"), publishedAt: "2024-10-29T08:00:00Z", upvotes: 2244, receipts: 4 },
  { id: "r-sai-12", collegeSlug: "sai-deemed-university", authorPseudonym: "Vermilion-02", authorYear: 3, authorBranch: "Biotech",
    rating: 2, truthScore: 36, title: "There are exactly two good professors.",
    body: "Both in biochemistry. Both close to retirement. The brochure shows seven faculty members. Four of those have left in the last 18 months. The poster is from 2021.",
    tags: ["faculty", "lies"], vibe: "warning", hasVideo: false,
    verification: verified("2024-07-04T10:00:00Z"), publishedAt: "2024-09-22T14:00:00Z", upvotes: 488, receipts: 1 },

  // ───────────────── NILA ARTS ─────────────────
  { id: "r-nila-01", collegeSlug: "nila-academy-of-arts", authorPseudonym: "Indigo-71", authorYear: 4, authorBranch: "Fine Arts",
    rating: 5, truthScore: 84, title: "This college genuinely loves its students.",
    body: "I have never been more challenged or more supported. The faculty know my name. They know my work. The brochure undersells the human warmth of this place. It oversells the visiting-artist roster.",
    tags: ["warmth", "faculty"], vibe: "warm", hasVideo: false,
    verification: verified("2024-04-10T10:00:00Z"), publishedAt: "2024-08-04T18:00:00Z", upvotes: 1102, receipts: 0 },
  { id: "r-nila-02", collegeSlug: "nila-academy-of-arts", authorPseudonym: "Ultramarine-08", authorYear: 3, authorBranch: "Graphic Design",
    rating: 4, truthScore: 70, title: "Studio space is brochure-lie #1.",
    body: "Fine Arts students each get a studio nook. Beautiful. Graphic Design — 4 to a desk. Shifts after 6 PM. The brochure photo with the lone designer at a sunlit window is staged. We've all sat at that desk in shifts.",
    tags: ["infrastructure", "branch-bias"], vibe: "deadpan", hasVideo: true,
    verification: verified("2024-06-19T10:00:00Z"), publishedAt: "2024-09-12T13:00:00Z", upvotes: 622, receipts: 2 },
  { id: "r-nila-03", collegeSlug: "nila-academy-of-arts", authorPseudonym: "Ochre-44", authorYear: 5, authorBranch: "Fine Arts (Alumni)",
    rating: 5, truthScore: 81, title: "The brochure is honest. The city isn't cheap.",
    body: "Pondicherry rents doubled in 5 years. Nila is honest about its hostel but cannot control what landlords charge once you move off-campus in Year 2. Plan your finances for 4 years, not the 'first-year discount' in the brochure.",
    tags: ["fees", "advice"], vibe: "warm", hasVideo: false,
    verification: { method: "alumni-roster", verifiedAt: "2024-03-08T10:00:00Z" }, publishedAt: "2024-07-22T15:00:00Z", upvotes: 488, receipts: 1 },
  { id: "r-nila-04", collegeSlug: "nila-academy-of-arts", authorPseudonym: "Cerulean-12", authorYear: 2, authorBranch: "Animation",
    rating: 3, truthScore: 58, title: "Visiting-artist roster is overstated.",
    body: "The brochure says Berlin, Tokyo, New York. In my four semesters I have seen two visiting artists in person, three more on Zoom. The faculty here is excellent — they don't need the visiting-artist fiction.",
    tags: ["faculty", "lies"], vibe: "deadpan", hasVideo: false,
    verification: verified("2024-07-12T10:00:00Z"), publishedAt: "2024-10-09T12:00:00Z", upvotes: 244, receipts: 1 },
  { id: "r-nila-05", collegeSlug: "nila-academy-of-arts", authorPseudonym: "Vermilion-66", authorYear: 4, authorBranch: "Graphic Design",
    rating: 5, truthScore: 76, title: "Placement support is real, but quiet.",
    body: "Nila doesn't run a job fair. It runs portfolio reviews. Six of us got placed at Wieden+Kennedy this year because one faculty member personally walked our books in. The brochure shows logos. The truth is one professor.",
    tags: ["placements", "warmth"], vibe: "warm", hasVideo: false,
    verification: verified("2024-05-04T10:00:00Z"), publishedAt: "2024-09-04T16:00:00Z", upvotes: 988, receipts: 2 },
  { id: "r-nila-06", collegeSlug: "nila-academy-of-arts", authorPseudonym: "Saffron-89", authorYear: 1, authorBranch: "Fine Arts",
    rating: 4, truthScore: 71, title: "The brochure didn't oversell the campus.",
    body: "11 acres feels enormous when you're a first-year. The promised 17 acres I am told includes a partner site you visit twice a year. Doesn't matter. The 11 acres are extraordinary.",
    tags: ["campus-life"], vibe: "warm", hasVideo: false,
    verification: verified("2024-10-02T10:00:00Z"), publishedAt: "2024-11-12T11:00:00Z", upvotes: 312, receipts: 0 },
  { id: "r-nila-07", collegeSlug: "nila-academy-of-arts", authorPseudonym: "Amaranth-55", authorYear: 5, authorBranch: "Animation (Alumni)",
    rating: 4, truthScore: 69, title: "The material costs are not in the brochure.",
    body: "Animation = drawing tablets, software licences, render time. ₹70k/year minimum, not in the published fee structure. Plan for it. The college will give you everything else.",
    tags: ["fees", "advice"], vibe: "deadpan", hasVideo: false,
    verification: { method: "alumni-roster", verifiedAt: "2024-02-14T10:00:00Z" }, publishedAt: "2024-08-11T14:00:00Z", upvotes: 411, receipts: 1 },
  { id: "r-nila-08", collegeSlug: "nila-academy-of-arts", authorPseudonym: "Madder-37", authorYear: 3, authorBranch: "Fine Arts",
    rating: 5, truthScore: 88, title: "My professor saw my work and didn't sleep that night.",
    body: "She emailed me at 2 AM. Three pages. The honest critique I would never have got at a 'bigger' college. The brochure says 'mentorship.' What it actually means is: you will be seen.",
    tags: ["warmth", "faculty"], vibe: "warm", hasVideo: false,
    verification: verified("2024-05-30T10:00:00Z"), publishedAt: "2024-09-29T20:00:00Z", upvotes: 1502, receipts: 0 },
  { id: "r-nila-09", collegeSlug: "nila-academy-of-arts", authorPseudonym: "Topaz-21", authorYear: 2, authorBranch: "Graphic Design",
    rating: 3, truthScore: 60, title: "Mental health support is two part-timers.",
    body: "Brochure mentions 'wellness centre.' Two counsellors, both part-time, for 600 students. Waiting list is 3-4 weeks. They try hard. The institution underfunds them. Plan privately if you can.",
    tags: ["mental-health", "lies"], vibe: "warning", hasVideo: false,
    verification: verified("2024-08-22T10:00:00Z"), publishedAt: "2024-10-04T11:00:00Z", upvotes: 588, receipts: 1 },
  { id: "r-nila-10", collegeSlug: "nila-academy-of-arts", authorPseudonym: "Pearl-64", authorYear: 4, authorBranch: "Fine Arts",
    rating: 5, truthScore: 79, title: "I learned to be an artist here. I will not say more.",
    body: "Some colleges teach. Nila inhabits. I cannot put this college in a star-rating without lying. 5 stars is closer than 4. The brochure tries to translate it into placements and rankings. It cannot.",
    tags: ["warmth"], vibe: "warm", hasVideo: false,
    verification: verified("2024-04-19T10:00:00Z"), publishedAt: "2024-08-29T17:00:00Z", upvotes: 922, receipts: 0 },
  { id: "r-nila-11", collegeSlug: "nila-academy-of-arts", authorPseudonym: "Loam-99", authorYear: 1, authorBranch: "Graphic Design",
    rating: 2, truthScore: 44, title: "The first-year curriculum is a foundation course.",
    body: "Brochure implies you start in your discipline. Year 1 = foundation across all disciplines. Useful in hindsight. Disappointing at the start, when you came here to do design.",
    tags: ["academics"], vibe: "warning", hasVideo: false,
    verification: verified("2024-10-22T10:00:00Z"), publishedAt: "2024-11-08T10:00:00Z", upvotes: 188, receipts: 0 },
  { id: "r-nila-12", collegeSlug: "nila-academy-of-arts", authorPseudonym: "Ash-18", authorYear: 5, authorBranch: "Graphic Design (Alumni)",
    rating: 4, truthScore: 71, title: "The brochure forgot to mention the sea.",
    body: "I lived in Pondicherry for four years. I learned typography. I learned that the sea changes colour in October. The brochure focused on classrooms. The sea was my classroom.",
    tags: ["warmth", "alumni"], vibe: "warm", hasVideo: false,
    verification: { method: "alumni-roster", verifiedAt: "2024-01-09T10:00:00Z" }, publishedAt: "2024-07-18T19:00:00Z", upvotes: 644, receipts: 0 },

  // ───────────────── ASIANOVA BUSINESS SCHOOL ─────────────────
  { id: "r-abs-01", collegeSlug: "asianova-business-school", authorPseudonym: "Mahogany-44", authorYear: 2, authorBranch: "MBA Finance",
    rating: 2, truthScore: 38, title: "The ranking is bought.",
    body: "Public filings show the magazine that publishes the #4 ranking is owned by a media group that takes paid 'brand engagement' from B-schools. ABS paid ₹38L last year. The ranking is on the cover. Do the math.",
    tags: ["lies", "rankings"], vibe: "rage", hasVideo: true,
    verification: verified("2024-09-04T10:00:00Z"), publishedAt: "2024-10-20T09:00:00Z", upvotes: 2188, receipts: 8 },
  { id: "r-abs-02", collegeSlug: "asianova-business-school", authorPseudonym: "Maple-21", authorYear: 2, authorBranch: "MBA Marketing",
    rating: 3, truthScore: 56, title: "Classrooms are the best thing here.",
    body: "Genuinely. The case-method rooms, the tech, the layout — better than my undergrad IIM. The faculty in those rooms is uneven. The brochure photo of the classroom does not lie.",
    tags: ["infrastructure"], vibe: "deadpan", hasVideo: false,
    verification: verified("2024-06-12T10:00:00Z"), publishedAt: "2024-09-14T11:00:00Z", upvotes: 433, receipts: 1 },
  { id: "r-abs-03", collegeSlug: "asianova-business-school", authorPseudonym: "Walnut-12", authorYear: 3, authorBranch: "MBA Finance (Alumni)",
    rating: 2, truthScore: 41, title: "Median CTC has an asterisk you can't see.",
    body: "₹17.4 LPA median, brochure. Look closely: includes ESOPs and 'expected bonuses over 3 years.' Actual cash-in-hand year-1 median: ₹11.2 LPA. I made the calculation 18 months in. I asked. The placement cell told me 'it's industry standard.'",
    tags: ["placements", "lies"], vibe: "rage", hasVideo: false,
    verification: { method: "alumni-roster", verifiedAt: "2024-02-19T10:00:00Z" }, publishedAt: "2024-08-30T13:00:00Z", upvotes: 1622, receipts: 4 },
  { id: "r-abs-04", collegeSlug: "asianova-business-school", authorPseudonym: "Birch-77", authorYear: 1, authorBranch: "MBA HR",
    rating: 3, truthScore: 54, title: "Faculty from Wharton: yes, technically.",
    body: "Three adjuncts. One elective each. Core curriculum: ABS faculty, competent but not the Wharton/INSEAD caliber. The brochure shows the adjuncts on the cover. They appear 90 minutes per week, max.",
    tags: ["faculty", "lies"], vibe: "deadpan", hasVideo: false,
    verification: verified("2024-09-14T10:00:00Z"), publishedAt: "2024-10-22T16:00:00Z", upvotes: 488, receipts: 1 },
  { id: "r-abs-05", collegeSlug: "asianova-business-school", authorPseudonym: "Ash-22", authorYear: 2, authorBranch: "MBA Operations",
    rating: 4, truthScore: 68, title: "Network is real. Curriculum, less so.",
    body: "The peer group at ABS is genuinely impressive. The curriculum is a HBR Greatest Hits with slides from 2018. You learn from your classmates. Worth it for that alone. Brochure forgot to lead with that.",
    tags: ["academics", "warmth"], vibe: "warm", hasVideo: false,
    verification: verified("2024-05-22T10:00:00Z"), publishedAt: "2024-09-08T17:00:00Z", upvotes: 712, receipts: 0 },
  { id: "r-abs-06", collegeSlug: "asianova-business-school", authorPseudonym: "Cedar-08", authorYear: 2, authorBranch: "MBA Strategy",
    rating: 1, truthScore: 28, title: "The international module is a 5-day Singapore trip.",
    body: "Brochure: 'International Module.' Reality: 5-day Singapore trip, ₹2.4L additional fee. Mandatory. Content: 4 lectures at a co-working space, 2 free days, group photo. The brochure has a photo of Stanford. Stanford is not involved.",
    tags: ["lies", "fees"], vibe: "rage", hasVideo: true,
    verification: verified("2024-08-30T10:00:00Z"), publishedAt: "2024-10-04T12:00:00Z", upvotes: 1944, receipts: 6 },
  { id: "r-abs-07", collegeSlug: "asianova-business-school", authorPseudonym: "Linden-93", authorYear: 3, authorBranch: "MBA (Alumni)",
    rating: 3, truthScore: 51, title: "I would do it again. Then I would negotiate.",
    body: "ABS got me a ₹14L offer. The brochure number said ₹17.4L. Realising I was below median pushed me to switch jobs in year 2 to ₹22L. So the brochure lie became my motivation. Strange way to measure ROI.",
    tags: ["placements", "redemption"], vibe: "redeemed", hasVideo: false,
    verification: { method: "alumni-roster", verifiedAt: "2024-03-04T10:00:00Z" }, publishedAt: "2024-09-20T18:00:00Z", upvotes: 522, receipts: 0 },
  { id: "r-abs-08", collegeSlug: "asianova-business-school", authorPseudonym: "Sumac-67", authorYear: 1, authorBranch: "MBA Finance",
    rating: 2, truthScore: 39, title: "Recruiter count is engagement, not hiring.",
    body: "Brochure: '380+ recruiters.' Actual on-campus hires came from 38 companies. The other 342 'engaged' via a 30-min Zoom on company-deep-dive day, or attended a coffee meet, or sent an email. 'Engaged' is doing a lot of work.",
    tags: ["placements", "lies"], vibe: "deadpan", hasVideo: false,
    verification: verified("2024-10-08T10:00:00Z"), publishedAt: "2024-11-04T10:00:00Z", upvotes: 877, receipts: 3 },
  { id: "r-abs-09", collegeSlug: "asianova-business-school", authorPseudonym: "Tamarind-58", authorYear: 2, authorBranch: "MBA Marketing",
    rating: 4, truthScore: 65, title: "If you network like your life depends on it.",
    body: "ABS rewards the extroverted. The cases, the cohort dinners, the alumni events — all gold if you show up. If you keep to yourself, you'll get a fine job at a fair salary and look back wondering what you missed.",
    tags: ["advice"], vibe: "warm", hasVideo: false,
    verification: verified("2024-06-04T10:00:00Z"), publishedAt: "2024-08-22T20:00:00Z", upvotes: 411, receipts: 0 },
  { id: "r-abs-10", collegeSlug: "asianova-business-school", authorPseudonym: "Hazel-39", authorYear: 2, authorBranch: "MBA Operations",
    rating: 3, truthScore: 57, title: "The placement cell coaches you to overstate.",
    body: "We were given a script for placement-survey responses. Include base + variable + expected bonus + 3-year ESOP. The brochure number is the script number. Almost nobody actually earns that.",
    tags: ["placements", "lies"], vibe: "warning", hasVideo: false,
    verification: verified("2024-07-22T10:00:00Z"), publishedAt: "2024-09-30T14:00:00Z", upvotes: 1188, receipts: 4 },
  { id: "r-abs-11", collegeSlug: "asianova-business-school", authorPseudonym: "Sorrel-71", authorYear: 1, authorBranch: "MBA HR",
    rating: 4, truthScore: 71, title: "Best decision for what it actually is.",
    body: "A regional B-school that punches above its weight if you network. A bad decision if you came expecting Wharton-South. Adjust expectations downward, get the experience, leave with the network.",
    tags: ["advice"], vibe: "redeemed", hasVideo: false,
    verification: verified("2024-09-19T10:00:00Z"), publishedAt: "2024-10-30T16:00:00Z", upvotes: 622, receipts: 0 },
  { id: "r-abs-12", collegeSlug: "asianova-business-school", authorPseudonym: "Sage-43", authorYear: 3, authorBranch: "MBA Finance (Alumni)",
    rating: 3, truthScore: 58, title: "Worth ₹16L. Charged ₹24L.",
    body: "That is the long and short of it. The brochure justifies ₹24L with rankings, faculty stars, and the median-CTC asterisk. The experience itself was worth, fairly, about ₹16L. The delta is the brand premium.",
    tags: ["fees"], vibe: "deadpan", hasVideo: false,
    verification: { method: "alumni-roster", verifiedAt: "2024-04-04T10:00:00Z" }, publishedAt: "2024-08-18T11:00:00Z", upvotes: 933, receipts: 1 },

  // ───────────────── KAVERI REGIONAL UNIVERSITY ─────────────────
  { id: "r-kru-01", collegeSlug: "kaveri-regional-university", authorPseudonym: "Cobalt-19", authorYear: 4, authorBranch: "B.Sc Physics",
    rating: 5, truthScore: 91, title: "The first college to undersell itself.",
    body: "Brochure: 6 pages. No glossy paper. No celebrity faculty photo. I came expecting the bare minimum. I left having learned more, from people who tried harder, than at any institution I have visited since.",
    tags: ["warmth"], vibe: "warm", hasVideo: false,
    verification: verified("2024-04-04T10:00:00Z"), publishedAt: "2024-08-04T17:00:00Z", upvotes: 1144, receipts: 0 },
  { id: "r-kru-02", collegeSlug: "kaveri-regional-university", authorPseudonym: "Slate-92", authorYear: 5, authorBranch: "B.Sc Chemistry (Alumni)",
    rating: 5, truthScore: 88, title: "Tuition: ₹14,000/year. The brochure didn't lie.",
    body: "I have not lived a day of regret about choosing Kaveri over a flashier college my family pressured me toward. The cost was real. The teaching was real. The job came from PSU exam prep, which the campus quietly supports.",
    tags: ["fees", "warmth"], vibe: "warm", hasVideo: false,
    verification: { method: "alumni-roster", verifiedAt: "2024-02-12T10:00:00Z" }, publishedAt: "2024-07-20T15:00:00Z", upvotes: 802, receipts: 0 },
  { id: "r-kru-03", collegeSlug: "kaveri-regional-university", authorPseudonym: "Ferrum-44", authorYear: 3, authorBranch: "B.A History",
    rating: 4, truthScore: 78, title: "Library is the best-kept secret in the state.",
    body: "Catalogue from 1981, complete. Three rare-manuscript rooms. A librarian who has been there 38 years and reads every book she catalogues. The brochure does not mention her by name. She is the institution.",
    tags: ["infrastructure", "warmth"], vibe: "warm", hasVideo: false,
    verification: verified("2024-05-22T10:00:00Z"), publishedAt: "2024-09-18T12:00:00Z", upvotes: 488, receipts: 0 },
  { id: "r-kru-04", collegeSlug: "kaveri-regional-university", authorPseudonym: "Carbon-77", authorYear: 2, authorBranch: "B.Sc CS",
    rating: 3, truthScore: 62, title: "CS curriculum is a decade behind.",
    body: "We still learn C++ as the primary language. Object-oriented design from a 2011 textbook. The faculty are kind, work hard, and are 10 years behind the industry. The brochure does not promise a modern curriculum. To its credit.",
    tags: ["academics", "infrastructure"], vibe: "deadpan", hasVideo: false,
    verification: verified("2024-08-04T10:00:00Z"), publishedAt: "2024-10-04T11:00:00Z", upvotes: 244, receipts: 1 },
  { id: "r-kru-05", collegeSlug: "kaveri-regional-university", authorPseudonym: "Marrow-88", authorYear: 4, authorBranch: "B.A English",
    rating: 5, truthScore: 86, title: "NSS programme is genuinely transformative.",
    body: "Two days a week for two years in nearby villages. Curriculum-integrated, faculty-led, no brochure photo-op. By graduation, half my class spoke fluent Tamil at a level the city kids never picked up. The brochure mentions 'community service' in one line. It deserves more.",
    tags: ["campus-life", "warmth"], vibe: "warm", hasVideo: false,
    verification: verified("2024-04-19T10:00:00Z"), publishedAt: "2024-08-30T16:00:00Z", upvotes: 612, receipts: 0 },
  { id: "r-kru-06", collegeSlug: "kaveri-regional-university", authorPseudonym: "Petal-31", authorYear: 1, authorBranch: "B.Sc Botany",
    rating: 4, truthScore: 75, title: "First-year orientation was a samosa and a speech.",
    body: "And it was perfect. No 18-page glossy welcome pack. No mandatory orientation kit. A samosa, a 12-minute speech from the principal, and a tour. I felt welcomed in a way the brochure could not have promised.",
    tags: ["warmth", "campus-life"], vibe: "warm", hasVideo: false,
    verification: verified("2024-10-19T10:00:00Z"), publishedAt: "2024-11-08T14:00:00Z", upvotes: 411, receipts: 0 },
  { id: "r-kru-07", collegeSlug: "kaveri-regional-university", authorPseudonym: "Talc-66", authorYear: 5, authorBranch: "B.Sc Maths (Alumni)",
    rating: 4, truthScore: 73, title: "Placement support is one person.",
    body: "Mrs. K. Sundari has been the placement officer for 14 years. She gets 41% of us placed on a budget of nearly nothing. She personally calls alumni for referrals. The brochure has no photo of her. She is the placement cell.",
    tags: ["placements", "warmth"], vibe: "warm", hasVideo: false,
    verification: { method: "alumni-roster", verifiedAt: "2024-03-19T10:00:00Z" }, publishedAt: "2024-09-04T13:00:00Z", upvotes: 902, receipts: 0 },
  { id: "r-kru-08", collegeSlug: "kaveri-regional-university", authorPseudonym: "Lichen-12", authorYear: 3, authorBranch: "B.Com",
    rating: 3, truthScore: 65, title: "Labs are functional, equipment is old.",
    body: "Old does not mean broken. It means thirty years of cumulative student fingerprints on every microscope, every multimeter, every titration setup. The brochure shows 'modern lab' which is a stretch. They work.",
    tags: ["infrastructure"], vibe: "deadpan", hasVideo: false,
    verification: verified("2024-07-04T10:00:00Z"), publishedAt: "2024-09-22T11:00:00Z", upvotes: 188, receipts: 0 },
  { id: "r-kru-09", collegeSlug: "kaveri-regional-university", authorPseudonym: "Quill-29", authorYear: 4, authorBranch: "B.A Tamil",
    rating: 5, truthScore: 93, title: "The smallest department has the biggest heart.",
    body: "There are 14 of us. Three faculty. We meet in a converted store-room with one fan. We have produced two state-level poetry prize winners in 3 years. The brochure does not mention Tamil. Honestly, that's fine.",
    tags: ["warmth"], vibe: "warm", hasVideo: false,
    verification: verified("2024-05-04T10:00:00Z"), publishedAt: "2024-08-19T16:00:00Z", upvotes: 622, receipts: 0 },
  { id: "r-kru-10", collegeSlug: "kaveri-regional-university", authorPseudonym: "Wick-51", authorYear: 2, authorBranch: "B.Sc Physics",
    rating: 4, truthScore: 76, title: "PSU exam culture is real and quiet.",
    body: "If you study for PSU exams here, half the campus is silently with you. Faculty share notes. Seniors share question papers. The brochure does not advertise this — but Kaveri quietly sends 12-14 students into PSU jobs every year.",
    tags: ["placements", "academics"], vibe: "warm", hasVideo: false,
    verification: verified("2024-08-19T10:00:00Z"), publishedAt: "2024-10-22T15:00:00Z", upvotes: 711, receipts: 1 },
  { id: "r-kru-11", collegeSlug: "kaveri-regional-university", authorPseudonym: "Onyx-04", authorYear: 5, authorBranch: "B.A History (Alumni)",
    rating: 4, truthScore: 79, title: "I am the brochure's most honest critic.",
    body: "The brochure undersold this place. Which is fine. They sold me what they could deliver. They delivered more. I would have paid 3x to attend. I paid ₹14k/year. I am, for the first time in my life, criticising a brochure for being too humble.",
    tags: ["warmth", "alumni"], vibe: "redeemed", hasVideo: false,
    verification: { method: "alumni-roster", verifiedAt: "2024-01-22T10:00:00Z" }, publishedAt: "2024-07-04T11:00:00Z", upvotes: 1244, receipts: 0 },
  { id: "r-kru-12", collegeSlug: "kaveri-regional-university", authorPseudonym: "Vine-87", authorYear: 1, authorBranch: "B.Sc Botany",
    rating: 4, truthScore: 71, title: "Wi-Fi is genuinely terrible.",
    body: "The brochure does not mention Wi-Fi. I now understand why. Plan accordingly. Bring a mobile data plan. Everything else here is better than the brochure suggested.",
    tags: ["infrastructure"], vibe: "deadpan", hasVideo: false,
    verification: verified("2024-10-04T10:00:00Z"), publishedAt: "2024-11-04T13:00:00Z", upvotes: 188, receipts: 0 },
];
